import {
  IsArray,
  IsBoolean,
  IsEnum,
  IsIn,
  IsObject,
  IsOptional,
  IsString,
  Matches,
  MaxLength,
  ValidateNested,
} from 'class-validator'
import { Type } from 'class-transformer'
import { LANGUAGE_CODES } from '@world-schools/wc-types'

export class UpdateBasicInfoDto {
  @IsOptional()
  @IsString()
  name?: string

  @IsOptional()
  @IsString()
  @MaxLength(150)
  @Matches(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, {
    message: 'Slug must be lowercase, alphanumeric, and use hyphens to separate words',
  })
  slug?: string

  @IsOptional()
  @IsEnum(['day', 'residential'])
  type?: 'day' | 'residential'

  @IsOptional()
  @IsString()
  description?: string

  @IsOptional()
  @IsEnum(['provider', 'different'])
  locationType?: 'provider' | 'different'

  @IsOptional()
  @IsString()
  locationPlaceId?: string

  @IsOptional()
  @IsString()
  locationName?: string

  @IsOptional()
  @IsString()
  locationAddress?: string

  @IsOptional()
  locationLat?: number

  @IsOptional()
  locationLng?: number

  @IsOptional()
  @IsArray()
  ageGroups?: any[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  @IsIn(LANGUAGE_CODES, { each: true })
  languages?: string[]

  @IsOptional()
  @IsEnum(['coed', 'boys', 'girls'])
  gender?: 'coed' | 'boys' | 'girls'

  @IsOptional()
  @IsArray()
  activities?: string[]

  /**
   * Payments revamp (Spec v2.3): per-listing "no deposit for this listing"
   * toggle. When false, the booking snapshot suppresses the deposit regardless
   * of the provider-level deposit setting (the whole price becomes balance).
   */
  @IsOptional()
  @IsBoolean()
  depositEnabled?: boolean
}

export class UpdatePhotosDto {
  @IsOptional()
  @IsObject()
  photos?: any
}

class InclusionItemIconDto {
  @IsString()
  type: string

  @IsString()
  name: string
}

class ManualInclusionItemDto {
  @IsString()
  id: string

  @IsString()
  @MaxLength(40)
  text: string

  @IsObject()
  @ValidateNested()
  @Type(() => InclusionItemIconDto)
  icon: InclusionItemIconDto

  @IsOptional()
  @IsString()
  source?: string

  @IsBoolean()
  isAutoGenerated: boolean

  @IsBoolean()
  isSelected: boolean
}

class AutoInclusionItemDto {
  @IsString()
  id: string

  @IsString()
  text: string

  @IsObject()
  @ValidateNested()
  @Type(() => InclusionItemIconDto)
  icon: InclusionItemIconDto

  @IsOptional()
  @IsString()
  source?: string

  @IsBoolean()
  isAutoGenerated: boolean

  @IsBoolean()
  isSelected: boolean
}

class WhatsIncludedDataDto {
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => AutoInclusionItemDto)
  autoGenerated?: AutoInclusionItemDto[]

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ManualInclusionItemDto)
  manual?: ManualInclusionItemDto[]
}

export class UpdateWhatsIncludedDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => WhatsIncludedDataDto)
  whatsIncluded?: WhatsIncludedDataDto
}

export class UpdateDailyScheduleDto {
  @IsOptional()
  @IsString()
  scheduleType?: string

  @IsOptional()
  @IsObject()
  dailySchedule?: any

  @IsOptional()
  @IsObject()
  weeklySchedule?: any
}

// Meals DTO
class MealsDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  mealTypes?: string[]

  @IsOptional()
  @IsString()
  mealStyle?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  dietaryOptions?: string[]
}

export class UpdateMealsDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => MealsDataDto)
  meals?: MealsDataDto
}

// Sports DTO
class SportsDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  skillLevel?: string

  @IsOptional()
  @IsString()
  coachingType?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedSports?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customSports?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  facilities?: string[]
}

export class UpdateSportsDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => SportsDataDto)
  sportsActivities?: SportsDataDto
}

// Languages DTO
class LanguagesDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  proficiency?: string

  @IsOptional()
  @IsString()
  methodology?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedLanguages?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customLanguages?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  certificates?: string[]
}

export class UpdateLanguagesDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => LanguagesDataDto)
  languagePrograms?: LanguagesDataDto
}

// Arts DTO
class ArtsDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  skillLevel?: string

  @IsOptional()
  @IsString()
  instructionType?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedArts?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customArts?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  supplies?: string[]
}

export class UpdateArtsDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => ArtsDataDto)
  artsAndCrafts?: ArtsDataDto
}

// Adventure DTO
class AdventureDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  difficultyLevel?: string

  @IsOptional()
  @IsString()
  supervisionRatio?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedActivities?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customActivities?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  certifications?: string[]
}

export class UpdateAdventureDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => AdventureDataDto)
  adventureActivities?: AdventureDataDto
}

// Water Activities DTO
class WaterDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  swimLevel?: string

  @IsOptional()
  @IsString()
  lifeguardCertification?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedActivities?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customActivities?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  facilities?: string[]
}

export class UpdateWaterDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => WaterDataDto)
  waterActivities?: WaterDataDto
}

// Environmental DTO
class EnvironmentalDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  sustainabilityFocus?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedActivities?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customActivities?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  certifications?: string[]
}

export class UpdateEnvironmentalDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => EnvironmentalDataDto)
  environmentalActivities?: EnvironmentalDataDto
}

// Academics DTO
class AcademicsDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  academicLevel?: string

  @IsOptional()
  @IsString()
  teachingApproach?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedSubjects?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customSubjects?: string[]
}

export class UpdateAcademicsDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => AcademicsDataDto)
  academics?: AcademicsDataDto
}

// Religion DTO
class ReligionDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  denomination?: string

  @IsOptional()
  @IsString()
  observance?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedPrograms?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customPrograms?: string[]
}

export class UpdateReligionDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => ReligionDataDto)
  religionPrograms?: ReligionDataDto
}

// Excursions DTO
class ExcursionsDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  transportIncluded?: string

  @IsOptional()
  @IsString()
  frequency?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedTrips?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customTrips?: string[]
}

export class UpdateExcursionsDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => ExcursionsDataDto)
  excursionsTrips?: ExcursionsDataDto
}

// Location & Campus DTO
class LocationCampusDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  campusSize?: string

  @IsOptional()
  @IsString()
  campusSetting?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedFacilities?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customFacilities?: string[]
}

export class UpdateLocationCampusDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => LocationCampusDataDto)
  campusFacilities?: LocationCampusDataDto
}

// Accommodation DTO
class AccommodationDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  roomCapacity?: string

  @IsOptional()
  @IsString()
  supervision?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedTypes?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  customTypes?: string[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  amenities?: string[]
}

export class UpdateAccommodationDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => AccommodationDataDto)
  accommodation?: AccommodationDataDto
}

// Getting There DTO
class GettingThereDataDto {
  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  transportIncluded?: string

  @IsOptional()
  @IsString()
  pickupLocations?: string

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  selectedTransport?: string[]

  @IsOptional()
  @IsObject()
  transportDetails?: Record<string, { description?: string }>
}

export class UpdateGettingThereDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => GettingThereDataDto)
  gettingThere?: GettingThereDataDto
}

// Camp Focus DTO - Single Primary Focus
class PrimaryFocusDto {
  @IsString()
  activityId: string

  @IsString()
  activityName: string

  @IsString()
  categoryId: string

  @IsString()
  categoryName: string

  @IsString()
  icon: string
}

class CampFocusDataDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => PrimaryFocusDto)
  primaryFocus?: PrimaryFocusDto | null

  @IsOptional()
  @IsString()
  @MaxLength(1200)
  description?: string

  @IsOptional()
  @IsString()
  philosophy?: string

  @IsOptional()
  @IsString()
  learningApproach?: string
}

export class UpdateCampFocusDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => CampFocusDataDto)
  campFocus?: CampFocusDataDto
}

export class UpdateCampStatusDto {
  @IsEnum(['draft', 'published', 'archived'])
  status: 'draft' | 'published' | 'archived'
}

// ─── Safety & Policies (combined) ────────────────────────────────────────────

class StaffRatioDto {
  @IsString()
  label: string

  @IsString()
  value: string
}

class SafetySupervisionDataDto {
  @IsOptional()
  @IsString()
  description?: string

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => StaffRatioDto)
  staffRatios?: StaffRatioDto[]

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  items?: string[]
}

class ScreenPolicyDataDto {
  @IsString()
  description: string
}

export class UpdateSafetyPoliciesDto {
  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => SafetySupervisionDataDto)
  safetySupervision?: SafetySupervisionDataDto | null

  @IsOptional()
  @IsObject()
  @ValidateNested()
  @Type(() => ScreenPolicyDataDto)
  screenPolicy?: ScreenPolicyDataDto | null
}
