'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { Button } from '@heroui/react'
import { IconRenderer, type IconValue, Input, LucideIconPicker } from '@world-schools/ui-web'
import { useCampsStore } from '../../../../../stores/camps-store'
import { AutoSaveIndicator } from '../../../../../components/camp-editor/AutoSaveIndicator'
import { generateAutoInclusions } from '../../../../../utils/generate-inclusions'
import type { InclusionItem, WhatsIncludedData } from '../../../../../types/whats-included'

const MAX_SELECTED_ITEMS = 12
const MAX_ITEM_LENGTH = 150

export default function WhatsIncludedEditorPage() {
  const params = useParams()
  const campId = params.campId as string

  const { currentCamp, updateSection } = useCampsStore()

  const [data, setData] = useState<WhatsIncludedData>({
    autoGenerated: [],
    manual: [],
  })

  const [newItemText, setNewItemText] = useState('')
  const [newItemIcon, setNewItemIcon] = useState<IconValue>({ type: 'lucide', name: 'Check' })
  const [autoSaveStatus, setAutoSaveStatus] = useState<'idle' | 'saving' | 'saved' | 'error'>(
    'idle'
  )
  const [saveTimeout, setSaveTimeout] = useState<NodeJS.Timeout | null>(null)

  // Load and generate inclusions
  useEffect(() => {
    if (currentCamp) {
      const freshAutoGenerated = generateAutoInclusions(currentCamp)

      // If we have existing data, merge fresh items with existing items
      if (currentCamp.whatsIncluded) {
        const existing = currentCamp.whatsIncluded as any

        // Check if there are any existing items (auto-generated or manual)
        const hasExistingItems =
          (existing.autoGenerated && existing.autoGenerated.length > 0) ||
          (existing.manual && existing.manual.length > 0)

        // Create maps for existing auto-generated items
        const existingItemsMap = new Map<string, InclusionItem>()
        const freshSourcesSet = new Set<string>()

        // Map existing items by source
        if (existing.autoGenerated && Array.isArray(existing.autoGenerated)) {
          existing.autoGenerated.forEach((item: InclusionItem) => {
            if (item.source) {
              existingItemsMap.set(item.source, item)
            }
          })
        }

        // Track which sources are in the fresh generation
        freshAutoGenerated.forEach(item => {
          if (item.source) {
            freshSourcesSet.add(item.source)
          }
        })

        // Merge fresh items with existing selection states
        const mergedAutoGenerated = freshAutoGenerated.map(item => {
          // If item exists in saved data, preserve its selection state
          if (item.source && existingItemsMap.has(item.source)) {
            return {
              ...item,
              isSelected: existingItemsMap.get(item.source)!.isSelected,
            }
          }

          // For new items:
          // - If there are existing items, default to false (don't auto-select new additions)
          // - If no existing items (first visit), default to true (pre-select for convenience)
          return {
            ...item,
            isSelected: !hasExistingItems,
          }
        })

        // Find orphaned items (existing items no longer auto-generated)
        const orphanedItems: InclusionItem[] = []
        existingItemsMap.forEach((item, source) => {
          if (!freshSourcesSet.has(source)) {
            orphanedItems.push(item)
          }
        })

        // Combine fresh items with orphaned items
        const finalAutoGenerated = [...mergedAutoGenerated, ...orphanedItems]

        setData({
          autoGenerated: finalAutoGenerated,
          manual: existing.manual || [],
        })
      } else {
        // No existing data - this is the first visit
        // Default all items to selected for a good initial experience
        setData({
          autoGenerated: freshAutoGenerated,
          manual: [],
        })
      }
    }
  }, [currentCamp])

  // Auto-save handler
  const triggerAutoSave = (updatedData: WhatsIncludedData) => {
    if (saveTimeout) {
      clearTimeout(saveTimeout)
    }

    setAutoSaveStatus('saving')
    // Update store to indicate pending auto-save (debounce period)
    useCampsStore.setState({ hasPendingAutoSave: true, autoSaveStatus: 'saving' })

    const timeout = setTimeout(async () => {
      try {
        await updateSection(campId, 'whats-included', { whatsIncluded: updatedData })
        setAutoSaveStatus('saved')
        useCampsStore.setState({ hasPendingAutoSave: false, autoSaveStatus: 'saved' })
        setTimeout(() => {
          setAutoSaveStatus('idle')
          useCampsStore.setState({ autoSaveStatus: 'idle' })
        }, 2000)
      } catch (error) {
        console.error('Failed to save whats included:', error)
        setAutoSaveStatus('error')
        useCampsStore.setState({ hasPendingAutoSave: false, autoSaveStatus: 'error' })
      }
    }, 1500)

    setSaveTimeout(timeout)
  }

  // Cleanup on unmount - clear pending auto-save state
  useEffect(() => {
    return () => {
      useCampsStore.setState({ hasPendingAutoSave: false, autoSaveStatus: 'idle' })
    }
  }, [])

  const toggleAutoItem = (itemId: string) => {
    const updated = {
      ...data,
      autoGenerated: data.autoGenerated.map(item =>
        item.id === itemId ? { ...item, isSelected: !item.isSelected } : item
      ),
    }
    setData(updated)
    triggerAutoSave(updated)
  }

  const addManualItem = () => {
    if (!newItemText.trim() || newItemText.length > MAX_ITEM_LENGTH) return

    const newItem: InclusionItem = {
      id: `manual-${Date.now()}`,
      text: newItemText.trim(),
      icon: newItemIcon,
      isAutoGenerated: false,
      isSelected: true,
    }

    const updated = {
      ...data,
      manual: [...data.manual, newItem],
    }

    setData(updated)
    setNewItemText('')
    setNewItemIcon({ type: 'lucide', name: 'Check' })
    triggerAutoSave(updated)
  }

  const deleteManualItem = (itemId: string) => {
    const updated = {
      ...data,
      manual: data.manual.filter(item => item.id !== itemId),
    }
    setData(updated)
    triggerAutoSave(updated)
  }

  const totalSelected =
    data.autoGenerated.filter(item => item.isSelected).length +
    data.manual.filter(item => item.isSelected).length

  const canAddMore = totalSelected < MAX_SELECTED_ITEMS

  return (
    <div>
      {/* Header */}
      <div className="mb-8 flex items-start justify-between">
        <div>
          <h1 className="mb-1.5 text-2xl font-semibold text-foreground">What's Included</h1>
          <p className="text-base leading-normal text-default-500">
            Choose up to {MAX_SELECTED_ITEMS} items to display on your camp profile
          </p>
        </div>
        <AutoSaveIndicator status={autoSaveStatus} />
      </div>

      <div className="space-y-8">
        {/* Selection Counter */}
        <div className="form-group">
          <div className="flex items-center justify-between rounded-lg bg-default-100 p-4">
            <div>
              <div className="text-sm font-semibold text-foreground">Items Selected</div>
              <div className="text-xs text-default-500">
                Maximum {MAX_SELECTED_ITEMS} items can be displayed
              </div>
            </div>
            <div className="flex items-center gap-2">
              <span
                className={`text-2xl font-bold ${totalSelected > MAX_SELECTED_ITEMS ? 'text-danger' : 'text-foreground'}`}
              >
                {totalSelected}
              </span>
              <span className="text-default-500">/ {MAX_SELECTED_ITEMS}</span>
            </div>
          </div>
          {totalSelected > MAX_SELECTED_ITEMS && (
            <div className="mt-3 rounded-lg bg-danger-50 p-3 text-sm text-danger dark:bg-danger-50/10">
              Please deselect {totalSelected - MAX_SELECTED_ITEMS} item(s) to meet the maximum limit
            </div>
          )}
        </div>

        {/* Auto-Generated Inclusions */}
        {data.autoGenerated.length > 0 && (
          <div className="form-group">
            <div className="mb-2.5 flex items-center gap-2">
              <label className="text-sm font-medium text-foreground">From Your Camp Details</label>
              <span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
                Auto-Generated
              </span>
            </div>
            <p className="mb-2.5 text-sm leading-normal text-default-500">
              These items are pulled from other sections. Click to select/deselect.
            </p>

            <div className="space-y-2">
              {data.autoGenerated.map(item => (
                <div
                  key={item.id}
                  onClick={() => toggleAutoItem(item.id)}
                  className={`flex cursor-pointer items-start gap-3 rounded-lg p-3 transition-all ${
                    item.isSelected
                      ? 'border-l-3 border-primary bg-primary/5'
                      : 'bg-default-100 hover:bg-default-200'
                  }`}
                >
                  <div className="mt-0.5 text-xl">
                    <IconRenderer icon={item.icon} size={20} />
                  </div>
                  <div className="flex-1">
                    <div className="text-sm font-medium text-foreground">{item.text}</div>
                    {item.source && (
                      <div className="mt-0.5 text-xs text-default-500">
                        From: {item.source} section
                      </div>
                    )}
                  </div>
                  {item.isSelected && (
                    <div className="mt-0.5 text-primary">
                      <svg
                        className="h-5 w-5"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          strokeWidth={2}
                          d="M5 13l4 4L19 7"
                        />
                      </svg>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Manual Additions */}
        <div className="form-group">
          <div className="mb-2.5 flex items-center gap-2">
            <label className="text-sm font-medium text-foreground">Manual Additions</label>
          </div>
          <p className="mb-2.5 text-sm leading-normal text-default-500">
            Add custom items not covered by other sections (max {MAX_ITEM_LENGTH} characters each)
          </p>

          {data.manual.length > 0 && (
            <div className="mb-4 space-y-2">
              {data.manual.map(item => (
                <div
                  key={item.id}
                  className="flex items-start gap-3 rounded-lg border-l-3 border-primary bg-primary/5 p-3"
                >
                  <div className="mt-0.5 text-xl">
                    <IconRenderer icon={item.icon} size={20} />
                  </div>
                  <div className="flex-1 text-sm font-medium text-foreground">{item.text}</div>
                  <button
                    type="button"
                    onClick={() => deleteManualItem(item.id)}
                    className="mt-0.5 text-default-500 transition-colors hover:text-danger"
                  >
                    <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M6 18L18 6M6 6l12 12"
                      />
                    </svg>
                  </button>
                </div>
              ))}
            </div>
          )}

          <div className="flex gap-3">
            <LucideIconPicker
              isDisabled={!canAddMore}
              value={newItemIcon.type === 'lucide' ? newItemIcon.name : undefined}
              onChange={name => setNewItemIcon({ type: 'lucide', name })}
              pickerPosition="top"
            />
            <Input
              placeholder="e.g., Camp t-shirt and water bottle"
              value={newItemText}
              onValueChange={setNewItemText}
              maxLength={MAX_ITEM_LENGTH}
              onKeyDown={e => {
                if (e.key === 'Enter') {
                  e.preventDefault()
                  addManualItem()
                }
              }}
              classNames={{ input: 'text-sm' }}
              isDisabled={!canAddMore}
            />
            <Button
              color="primary"
              onPress={addManualItem}
              isDisabled={!newItemText.trim() || !canAddMore}
            >
              Add Item
            </Button>
          </div>
          {!canAddMore && (
            <div className="mt-2 text-xs text-warning">
              Maximum {MAX_SELECTED_ITEMS} items selected. Deselect items to add more.
            </div>
          )}
          <div className="mt-1.5 text-xs text-default-500">
            {newItemText.length} / {MAX_ITEM_LENGTH} characters
          </div>
        </div>
      </div>
    </div>
  )
}
