import { Check } from 'lucide-react'

interface IncludedItem {
  id: string
  text: string
  icon: string
  source?: string
  isAutoGenerated: boolean
  isSelected: boolean
}

interface IncludedGridProps {
  items: IncludedItem[]
  className?: string
}

export function IncludedGrid({ items, className = '' }: IncludedGridProps) {
  if (!items || items.length === 0) return null

  return (
    <div className={`grid grid-cols-2 gap-3 ${className}`}>
      {items.map(item => (
        <div key={item.id} className="flex items-center gap-2 text-sm text-gray-900">
          <Check className="w-5 h-5 text-primary shrink-0" strokeWidth={2.5} />
          <span className="flex-1">{item.text}</span>
        </div>
      ))}
    </div>
  )
}
