import { IconRenderer, type IconValue } from '@world-schools/ui-web'

interface IncludedItem {
  id: string
  text: string
  icon: IconValue | string
  source?: string
  isAutoGenerated: boolean
  isSelected: boolean
}

interface IncludedGridProps {
  items: IncludedItem[]
  className?: string
}

function renderIcon(icon: IconValue | string) {
  if (typeof icon === 'string') return <span>{icon}</span>
  return <IconRenderer icon={icon} size={18} />
}

export function IncludedGrid({ items, className = '' }: IncludedGridProps) {
  if (!items || items.length === 0) return null

  return (
    <div className={`grid grid-cols-2 gap-3 ${className}`}>
      {items.map(item => (
        <div key={item.id} className="flex items-center gap-2 text-gray-900 leading-relaxed">
          {renderIcon(item.icon)}
          <span className="flex-1">{item.text}</span>
        </div>
      ))}
    </div>
  )
}
