import type { Camp } from '../types/camps'
import type { InclusionItem } from '../types/whats-included'

/**
 * Generate auto-inclusions from camp data
 * This pulls relevant information from accommodation, meals, sports, arts, and languages sections
 */
export function generateAutoInclusions(camp: Camp): InclusionItem[] {
  const inclusions: InclusionItem[] = []
  let idCounter = 1

  // From Accommodation
  if (camp.accommodation) {
    const accommodation = camp.accommodation as any
    if (accommodation.selectedTypes && accommodation.selectedTypes.length > 0) {
      const types = accommodation.selectedTypes.join(', ')
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: `${types} accommodation`,
        icon: '🏠',
        source: 'Accommodation',
        isAutoGenerated: true,
        isSelected: true,
      })
    }
  }

  // From Meals
  if (camp.meals) {
    const meals = camp.meals as any
    if (meals.mealsIncluded && meals.mealsIncluded.length > 0) {
      const mealCount = meals.mealsIncluded.length
      const mealText =
        mealCount === 3 ? '3 meals daily (breakfast, lunch, dinner)' : `${mealCount} meals daily`
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: mealText,
        icon: '🍽️',
        source: 'Meals',
        isAutoGenerated: true,
        isSelected: true,
      })
    }

    if (meals.dietaryOptions && meals.dietaryOptions.length > 0) {
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: 'Dietary accommodations available',
        icon: '🥗',
        source: 'Meals',
        isAutoGenerated: true,
        isSelected: true,
      })
    }
  }

  // From Sports
  if (camp.sportsActivities) {
    const sports = camp.sportsActivities as any
    if (sports.selectedSports && sports.selectedSports.length > 0) {
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: 'Daily sports coaching and activities',
        icon: '⚽',
        source: 'Sports',
        isAutoGenerated: true,
        isSelected: true,
      })
    }
  }

  // From Arts
  if (camp.artsAndCrafts) {
    const arts = camp.artsAndCrafts as any
    if (arts.selectedArts && arts.selectedArts.length > 0) {
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: 'Arts and crafts materials',
        icon: '🎨',
        source: 'Arts',
        isAutoGenerated: true,
        isSelected: true,
      })
    }
  }

  // From Languages
  if (camp.languagePrograms) {
    const languages = camp.languagePrograms as any
    if (languages.selectedLanguages && languages.selectedLanguages.length > 0) {
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: 'Language instruction and materials',
        icon: '🗣️',
        source: 'Languages',
        isAutoGenerated: true,
        isSelected: true,
      })
    }
  }

  // From Adventure Activities
  if (camp.adventureActivities) {
    const adventure = camp.adventureActivities as any
    if (adventure.selectedActivities && adventure.selectedActivities.length > 0) {
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: 'Adventure activities and equipment',
        icon: '🏔️',
        source: 'Adventure',
        isAutoGenerated: true,
        isSelected: true,
      })
    }
  }

  // From Water Activities
  if (camp.waterActivities) {
    const water = camp.waterActivities as any
    if (water.selectedActivities && water.selectedActivities.length > 0) {
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: 'Water activities and safety equipment',
        icon: '🏊',
        source: 'Water Activities',
        isAutoGenerated: true,
        isSelected: true,
      })
    }
  }

  // From Excursions
  if (camp.excursionsTrips) {
    const excursions = camp.excursionsTrips as any
    if (excursions.selectedExcursions && excursions.selectedExcursions.length > 0) {
      inclusions.push({
        id: `auto-${idCounter++}`,
        text: 'Excursions and field trips',
        icon: '🚌',
        source: 'Excursions',
        isAutoGenerated: true,
        isSelected: true,
      })
    }
  }

  return inclusions
}
