import type { Camp } from '../types/camps'
import type { InclusionItem } from '../types/whats-included'

/**
 * Activity category to inclusion mapping
 * Maps activity categories from camp.activities to auto-generated inclusion items
 */
const ACTIVITY_INCLUSIONS: Record<string, { text: string; icon: string; source: string }> = {
  sports: {
    text: 'Daily sports coaching and activities',
    icon: '⚽',
    source: 'Sports',
  },
  languages: {
    text: 'Language instruction and materials',
    icon: '🗣️',
    source: 'Languages',
  },
  arts: {
    text: 'Arts and crafts materials',
    icon: '�',
    source: 'Arts',
  },
  adventure: {
    text: 'Adventure activities and equipment',
    icon: '🏔️',
    source: 'Adventure',
  },
  water: {
    text: 'Water activities and safety equipment',
    icon: '🏊',
    source: 'Water Activities',
  },
  environment: {
    text: 'Environmental education programs',
    icon: '🌱',
    source: 'Environmental',
  },
  academics: {
    text: 'Academic programs and materials',
    icon: '📚',
    source: 'Academics',
  },
  religion: {
    text: 'Religious programs and activities',
    icon: '🕊️',
    source: 'Religion',
  },
  excursions: {
    text: 'Excursions and field trips',
    icon: '🚌',
    source: 'Excursions',
  },
}

/**
 * Generate a stable, unique ID from a source string
 * Converts source to lowercase and replaces spaces with hyphens
 */
function generateIdFromSource(source: string): string {
  return `auto-${source.toLowerCase().replace(/\s+/g, '-')}`
}

/**
 * Generate auto-inclusions from camp data
 * Uses camp.activities array as the primary source of truth for activity-based inclusions
 * IDs are generated from the source field to ensure uniqueness and stability
 */
export function generateAutoInclusions(camp: Camp): InclusionItem[] {
  const inclusions: InclusionItem[] = []

  // Generate inclusions from activities array
  if (camp.activities && camp.activities.length > 0) {
    camp.activities.forEach(activity => {
      const inclusionConfig = ACTIVITY_INCLUSIONS[activity]
      if (inclusionConfig) {
        inclusions.push({
          id: generateIdFromSource(inclusionConfig.source),
          text: inclusionConfig.text,
          icon: inclusionConfig.icon,
          source: inclusionConfig.source,
          isAutoGenerated: true,
          isSelected: false,
        })
      }
    })
  }

  // From Accommodation
  if (camp.accommodation) {
    const accommodation = camp.accommodation as any
    if (accommodation.selectedTypes && accommodation.selectedTypes.length > 0) {
      const types = accommodation.selectedTypes.join(', ')
      inclusions.push({
        id: generateIdFromSource('Accommodation'),
        text: `${types} accommodation`,
        icon: '🏠',
        source: 'Accommodation',
        isAutoGenerated: true,
        isSelected: false,
      })
    }
  }

  // From Meals
  if (camp.meals) {
    const meals = camp.meals as any
    if (meals.mealsIncluded && meals.mealsIncluded.length > 0) {
      const mealCount = meals.mealsIncluded.length
      const mealText =
        mealCount === 3 ? '3 meals daily (breakfast, lunch, dinner)' : `${mealCount} meals daily`
      inclusions.push({
        id: generateIdFromSource('Meals'),
        text: mealText,
        icon: '🍽️',
        source: 'Meals',
        isAutoGenerated: true,
        isSelected: false,
      })
    }

    if (meals.dietaryOptions && meals.dietaryOptions.length > 0) {
      inclusions.push({
        id: generateIdFromSource('Meals-Dietary'),
        text: 'Dietary accommodations available',
        icon: '🥗',
        source: 'Meals-Dietary',
        isAutoGenerated: true,
        isSelected: false,
      })
    }
  }

  return inclusions
}
