export interface InclusionItem {
  id: string
  text: string
  icon: string
  source?: string
  isAutoGenerated: boolean
  isSelected: boolean
}

export interface WhatsIncludedData {
  autoGenerated: InclusionItem[]
  manual: InclusionItem[]
}
