import type { IconValue } from '@world-schools/ui-web'

export type { IconValue }

export interface InclusionItem {
  id: string
  text: string
  icon: IconValue
  source?: string
  isAutoGenerated: boolean
  isSelected: boolean
}

export interface WhatsIncludedData {
  autoGenerated: InclusionItem[]
  manual: InclusionItem[]
}
