-- ============================================================================
-- Country / nationality data migration: display names -> ISO 3166-1 alpha-2.
--
-- Run manually against LOCAL and STAGING databases. There is no production data
-- yet, so this is intentionally NOT a Prisma migration.
--
-- Idempotent & safe to re-run: each UPDATE only touches rows whose value still
-- matches a known display name / demonym. Once converted to a code, the row no
-- longer matches and is skipped. Unknown / already-migrated values are left
-- untouched.
-- ============================================================================

BEGIN;

-- users.country : country name -> ISO2 code
UPDATE users AS u
SET country = m.code
FROM (VALUES
    ('Afghanistan', 'AF'),
    ('Åland Islands', 'AX'),
    ('Albania', 'AL'),
    ('Algeria', 'DZ'),
    ('American Samoa', 'AS'),
    ('Andorra', 'AD'),
    ('Angola', 'AO'),
    ('Anguilla', 'AI'),
    ('Antarctica', 'AQ'),
    ('Antigua and Barbuda', 'AG'),
    ('Arab Republic of Egypt', 'EG'),
    ('Argentina', 'AR'),
    ('Argentine Republic', 'AR'),
    ('Armenia', 'AM'),
    ('Aruba', 'AW'),
    ('Australia', 'AU'),
    ('Austria', 'AT'),
    ('Azerbaijan', 'AZ'),
    ('Bahamas', 'BS'),
    ('Bahrain', 'BH'),
    ('Bailiwick of Guernsey', 'GG'),
    ('Bailiwick of Jersey', 'JE'),
    ('Bangladesh', 'BD'),
    ('Barbados', 'BB'),
    ('Belarus', 'BY'),
    ('Belgium', 'BE'),
    ('Belize', 'BZ'),
    ('Benin', 'BJ'),
    ('Bermuda', 'BM'),
    ('Bhutan', 'BT'),
    ('Bolivarian Republic of Venezuela', 'VE'),
    ('Bolivia', 'BO'),
    ('Bonaire, Sint Eustatius and Saba', 'BQ'),
    ('Bosnia and Herzegovina', 'BA'),
    ('Botswana', 'BW'),
    ('Bouvet Island', 'BV'),
    ('Brazil', 'BR'),
    ('British Indian Ocean Territory', 'IO'),
    ('British Virgin Islands', 'VG'),
    ('Brunei', 'BN'),
    ('Bulgaria', 'BG'),
    ('Burkina Faso', 'BF'),
    ('Burundi', 'BI'),
    ('Cambodia', 'KH'),
    ('Cameroon', 'CM'),
    ('Canada', 'CA'),
    ('Cape Verde', 'CV'),
    ('Caribbean Netherlands', 'BQ'),
    ('Cayman Islands', 'KY'),
    ('Central African Republic', 'CF'),
    ('Chad', 'TD'),
    ('Chile', 'CL'),
    ('China', 'CN'),
    ('Christmas Island', 'CX'),
    ('Co-operative Republic of Guyana', 'GY'),
    ('Cocos (Keeling) Islands', 'CC'),
    ('Collectivity of Saint Barthélemy', 'BL'),
    ('Colombia', 'CO'),
    ('Commonwealth of Australia', 'AU'),
    ('Commonwealth of Dominica', 'DM'),
    ('Commonwealth of Puerto Rico', 'PR'),
    ('Commonwealth of the Bahamas', 'BS'),
    ('Commonwealth of the Northern Mariana Islands', 'MP'),
    ('Comoros', 'KM'),
    ('Cook Islands', 'CK'),
    ('Costa Rica', 'CR'),
    ('Country of Curaçao', 'CW'),
    ('Croatia', 'HR'),
    ('Cuba', 'CU'),
    ('Curaçao', 'CW'),
    ('Cyprus', 'CY'),
    ('Czech Republic', 'CZ'),
    ('Czechia', 'CZ'),
    ('Democratic People''s Republic of Korea', 'KP'),
    ('Democratic Republic of São Tomé and Príncipe', 'ST'),
    ('Democratic Republic of the Congo', 'CD'),
    ('Democratic Republic of Timor-Leste', 'TL'),
    ('Democratic Socialist Republic of Sri Lanka', 'LK'),
    ('Denmark', 'DK'),
    ('Department of Mayotte', 'YT'),
    ('Djibouti', 'DJ'),
    ('Dominica', 'DM'),
    ('Dominican Republic', 'DO'),
    ('DR Congo', 'CD'),
    ('Ecuador', 'EC'),
    ('Egypt', 'EG'),
    ('El Salvador', 'SV'),
    ('Equatorial Guinea', 'GQ'),
    ('Eritrea', 'ER'),
    ('Estonia', 'EE'),
    ('Eswatini', 'SZ'),
    ('Ethiopia', 'ET'),
    ('Falkland Islands', 'FK'),
    ('Faroe Islands', 'FO'),
    ('Federal Democratic Republic of Ethiopia', 'ET'),
    ('Federal Democratic Republic of Nepal', 'NP'),
    ('Federal Republic of Germany', 'DE'),
    ('Federal Republic of Nigeria', 'NG'),
    ('Federal Republic of Somalia', 'SO'),
    ('Federated States of Micronesia', 'FM'),
    ('Federation of Saint Christopher and Nevis', 'KN'),
    ('Federative Republic of Brazil', 'BR'),
    ('Fiji', 'FJ'),
    ('Finland', 'FI'),
    ('France', 'FR'),
    ('French Guiana', 'GF'),
    ('French Polynesia', 'PF'),
    ('French Republic', 'FR'),
    ('French Southern and Antarctic Lands', 'TF'),
    ('Gabon', 'GA'),
    ('Gabonese Republic', 'GA'),
    ('Gambia', 'GM'),
    ('Georgia', 'GE'),
    ('Germany', 'DE'),
    ('Ghana', 'GH'),
    ('Gibraltar', 'GI'),
    ('Grand Duchy of Luxembourg', 'LU'),
    ('Greece', 'GR'),
    ('Greenland', 'GL'),
    ('Grenada', 'GD'),
    ('Guadeloupe', 'GP'),
    ('Guam', 'GU'),
    ('Guatemala', 'GT'),
    ('Guernsey', 'GG'),
    ('Guiana', 'GF'),
    ('Guinea', 'GN'),
    ('Guinea-Bissau', 'GW'),
    ('Guyana', 'GY'),
    ('Haiti', 'HT'),
    ('Hashemite Kingdom of Jordan', 'JO'),
    ('Heard Island and McDonald Islands', 'HM'),
    ('Hellenic Republic', 'GR'),
    ('Honduras', 'HN'),
    ('Hong Kong', 'HK'),
    ('Hong Kong Special Administrative Region of the People''s Republic of China', 'HK'),
    ('Hungary', 'HU'),
    ('Iceland', 'IS'),
    ('Independent and Sovereign Republic of Kiribati', 'KI'),
    ('Independent State of Papua New Guinea', 'PG'),
    ('Independent State of Samoa', 'WS'),
    ('India', 'IN'),
    ('Indonesia', 'ID'),
    ('Iran', 'IR'),
    ('Iraq', 'IQ'),
    ('Ireland', 'IE'),
    ('Islamic Republic of Afghanistan', 'AF'),
    ('Islamic Republic of Iran', 'IR'),
    ('Islamic Republic of Mauritania', 'MR'),
    ('Islamic Republic of Pakistan', 'PK'),
    ('Isle of Man', 'IM'),
    ('Israel', 'IL'),
    ('Italian Republic', 'IT'),
    ('Italy', 'IT'),
    ('Ivory Coast', 'CI'),
    ('Jamaica', 'JM'),
    ('Japan', 'JP'),
    ('Jersey', 'JE'),
    ('Jordan', 'JO'),
    ('Kazakhstan', 'KZ'),
    ('Kenya', 'KE'),
    ('Kingdom of Bahrain', 'BH'),
    ('Kingdom of Belgium', 'BE'),
    ('Kingdom of Bhutan', 'BT'),
    ('Kingdom of Cambodia', 'KH'),
    ('Kingdom of Denmark', 'DK'),
    ('Kingdom of Eswatini', 'SZ'),
    ('Kingdom of Lesotho', 'LS'),
    ('Kingdom of Morocco', 'MA'),
    ('Kingdom of Norway', 'NO'),
    ('Kingdom of Saudi Arabia', 'SA'),
    ('Kingdom of Spain', 'ES'),
    ('Kingdom of Sweden', 'SE'),
    ('Kingdom of Thailand', 'TH'),
    ('Kingdom of the Netherlands', 'NL'),
    ('Kingdom of Tonga', 'TO'),
    ('Kiribati', 'KI'),
    ('Kosovo', 'XK'),
    ('Kuwait', 'KW'),
    ('Kyrgyz Republic', 'KG'),
    ('Kyrgyzstan', 'KG'),
    ('Lao People''s Democratic Republic', 'LA'),
    ('Laos', 'LA'),
    ('Latvia', 'LV'),
    ('Lebanese Republic', 'LB'),
    ('Lebanon', 'LB'),
    ('Lesotho', 'LS'),
    ('Liberia', 'LR'),
    ('Libya', 'LY'),
    ('Liechtenstein', 'LI'),
    ('Lithuania', 'LT'),
    ('Luxembourg', 'LU'),
    ('Macao Special Administrative Region of the People''s Republic of China', 'MO'),
    ('Macau', 'MO'),
    ('Madagascar', 'MG'),
    ('Malawi', 'MW'),
    ('Malaysia', 'MY'),
    ('Maldives', 'MV'),
    ('Mali', 'ML'),
    ('Malta', 'MT'),
    ('Marshall Islands', 'MH'),
    ('Martinique', 'MQ'),
    ('Mauritania', 'MR'),
    ('Mauritius', 'MU'),
    ('Mayotte', 'YT'),
    ('Mexico', 'MX'),
    ('Micronesia', 'FM'),
    ('Moldova', 'MD'),
    ('Monaco', 'MC'),
    ('Mongolia', 'MN'),
    ('Montenegro', 'ME'),
    ('Montserrat', 'MS'),
    ('Morocco', 'MA'),
    ('Most Serene Republic of San Marino', 'SM'),
    ('Mozambique', 'MZ'),
    ('Myanmar', 'MM'),
    ('Namibia', 'NA'),
    ('Nation of Brunei, Abode of Peace', 'BN'),
    ('Nauru', 'NR'),
    ('Nepal', 'NP'),
    ('Netherlands', 'NL'),
    ('New Caledonia', 'NC'),
    ('New Zealand', 'NZ'),
    ('Nicaragua', 'NI'),
    ('Niger', 'NE'),
    ('Nigeria', 'NG'),
    ('Niue', 'NU'),
    ('Norfolk Island', 'NF'),
    ('North Korea', 'KP'),
    ('North Macedonia', 'MK'),
    ('Northern Mariana Islands', 'MP'),
    ('Norway', 'NO'),
    ('Oman', 'OM'),
    ('Oriental Republic of Uruguay', 'UY'),
    ('Pakistan', 'PK'),
    ('Palau', 'PW'),
    ('Palestine', 'PS'),
    ('Panama', 'PA'),
    ('Papua New Guinea', 'PG'),
    ('Paraguay', 'PY'),
    ('People''s Democratic Republic of Algeria', 'DZ'),
    ('People''s Republic of Bangladesh', 'BD'),
    ('People''s Republic of China', 'CN'),
    ('Peru', 'PE'),
    ('Philippines', 'PH'),
    ('Pitcairn Group of Islands', 'PN'),
    ('Pitcairn Islands', 'PN'),
    ('Plurinational State of Bolivia', 'BO'),
    ('Poland', 'PL'),
    ('Portugal', 'PT'),
    ('Portuguese Republic', 'PT'),
    ('Principality of Andorra', 'AD'),
    ('Principality of Liechtenstein', 'LI'),
    ('Principality of Monaco', 'MC'),
    ('Puerto Rico', 'PR'),
    ('Qatar', 'QA'),
    ('Republic of Albania', 'AL'),
    ('Republic of Angola', 'AO'),
    ('Republic of Armenia', 'AM'),
    ('Republic of Austria', 'AT'),
    ('Republic of Azerbaijan', 'AZ'),
    ('Republic of Belarus', 'BY'),
    ('Republic of Benin', 'BJ'),
    ('Republic of Botswana', 'BW'),
    ('Republic of Bulgaria', 'BG'),
    ('Republic of Burundi', 'BI'),
    ('Republic of Cabo Verde', 'CV'),
    ('Republic of Cameroon', 'CM'),
    ('Republic of Chad', 'TD'),
    ('Republic of Chile', 'CL'),
    ('Republic of China (Taiwan)', 'TW'),
    ('Republic of Colombia', 'CO'),
    ('Republic of Costa Rica', 'CR'),
    ('Republic of Côte d''Ivoire', 'CI'),
    ('Republic of Croatia', 'HR'),
    ('Republic of Cuba', 'CU'),
    ('Republic of Cyprus', 'CY'),
    ('Republic of Djibouti', 'DJ'),
    ('Republic of Ecuador', 'EC'),
    ('Republic of El Salvador', 'SV'),
    ('Republic of Equatorial Guinea', 'GQ'),
    ('Republic of Estonia', 'EE'),
    ('Republic of Fiji', 'FJ'),
    ('Republic of Finland', 'FI'),
    ('Republic of Ghana', 'GH'),
    ('Republic of Guatemala', 'GT'),
    ('Republic of Guinea', 'GN'),
    ('Republic of Guinea-Bissau', 'GW'),
    ('Republic of Haiti', 'HT'),
    ('Republic of Honduras', 'HN'),
    ('Republic of India', 'IN'),
    ('Republic of Indonesia', 'ID'),
    ('Republic of Iraq', 'IQ'),
    ('Republic of Ireland', 'IE'),
    ('Republic of Kazakhstan', 'KZ'),
    ('Republic of Kenya', 'KE'),
    ('Republic of Korea', 'KR'),
    ('Republic of Kosovo', 'XK'),
    ('Republic of Latvia', 'LV'),
    ('Republic of Liberia', 'LR'),
    ('Republic of Lithuania', 'LT'),
    ('Republic of Madagascar', 'MG'),
    ('Republic of Malawi', 'MW'),
    ('Republic of Mali', 'ML'),
    ('Republic of Malta', 'MT'),
    ('Republic of Mauritius', 'MU'),
    ('Republic of Moldova', 'MD'),
    ('Republic of Mozambique', 'MZ'),
    ('Republic of Namibia', 'NA'),
    ('Republic of Nauru', 'NR'),
    ('Republic of Nicaragua', 'NI'),
    ('Republic of Niger', 'NE'),
    ('Republic of North Macedonia', 'MK'),
    ('Republic of Palau', 'PW'),
    ('Republic of Panama', 'PA'),
    ('Republic of Paraguay', 'PY'),
    ('Republic of Peru', 'PE'),
    ('Republic of Poland', 'PL'),
    ('Republic of Rwanda', 'RW'),
    ('Republic of Senegal', 'SN'),
    ('Republic of Serbia', 'RS'),
    ('Republic of Seychelles', 'SC'),
    ('Republic of Sierra Leone', 'SL'),
    ('Republic of Singapore', 'SG'),
    ('Republic of Slovenia', 'SI'),
    ('Republic of South Africa', 'ZA'),
    ('Republic of South Sudan', 'SS'),
    ('Republic of Suriname', 'SR'),
    ('Republic of Tajikistan', 'TJ'),
    ('Republic of the Congo', 'CG'),
    ('Republic of the Gambia', 'GM'),
    ('Republic of the Maldives', 'MV'),
    ('Republic of the Marshall Islands', 'MH'),
    ('Republic of the Philippines', 'PH'),
    ('Republic of the Sudan', 'SD'),
    ('Republic of the Union of Myanmar', 'MM'),
    ('Republic of Trinidad and Tobago', 'TT'),
    ('Republic of Türkiye', 'TR'),
    ('Republic of Uganda', 'UG'),
    ('Republic of Uzbekistan', 'UZ'),
    ('Republic of Vanuatu', 'VU'),
    ('Republic of Yemen', 'YE'),
    ('Republic of Zambia', 'ZM'),
    ('Republic of Zimbabwe', 'ZW'),
    ('Réunion', 'RE'),
    ('Réunion Island', 'RE'),
    ('Romania', 'RO'),
    ('Russia', 'RU'),
    ('Russian Federation', 'RU'),
    ('Rwanda', 'RW'),
    ('Sahrawi Arab Democratic Republic', 'EH'),
    ('Saint Barthélemy', 'BL'),
    ('Saint Helena, Ascension and Tristan da Cunha', 'SH'),
    ('Saint Kitts and Nevis', 'KN'),
    ('Saint Lucia', 'LC'),
    ('Saint Martin', 'MF'),
    ('Saint Pierre and Miquelon', 'PM'),
    ('Saint Vincent and the Grenadines', 'VC'),
    ('Samoa', 'WS'),
    ('San Marino', 'SM'),
    ('São Tomé and Príncipe', 'ST'),
    ('Saudi Arabia', 'SA'),
    ('Senegal', 'SN'),
    ('Serbia', 'RS'),
    ('Seychelles', 'SC'),
    ('Sierra Leone', 'SL'),
    ('Singapore', 'SG'),
    ('Sint Maarten', 'SX'),
    ('Slovak Republic', 'SK'),
    ('Slovakia', 'SK'),
    ('Slovenia', 'SI'),
    ('Socialist Republic of Vietnam', 'VN'),
    ('Solomon Islands', 'SB'),
    ('Somalia', 'SO'),
    ('South Africa', 'ZA'),
    ('South Georgia', 'GS'),
    ('South Georgia and the South Sandwich Islands', 'GS'),
    ('South Korea', 'KR'),
    ('South Sudan', 'SS'),
    ('Spain', 'ES'),
    ('Sri Lanka', 'LK'),
    ('State of Eritrea', 'ER'),
    ('State of Israel', 'IL'),
    ('State of Kuwait', 'KW'),
    ('State of Libya', 'LY'),
    ('State of Palestine', 'PS'),
    ('State of Qatar', 'QA'),
    ('Sudan', 'SD'),
    ('Sultanate of Oman', 'OM'),
    ('Suriname', 'SR'),
    ('Svalbard and Jan Mayen', 'SJ'),
    ('Svalbard og Jan Mayen', 'SJ'),
    ('Sweden', 'SE'),
    ('Swiss Confederation', 'CH'),
    ('Switzerland', 'CH'),
    ('Syria', 'SY'),
    ('Syrian Arab Republic', 'SY'),
    ('Taiwan', 'TW'),
    ('Tajikistan', 'TJ'),
    ('Tanzania', 'TZ'),
    ('Territory of Christmas Island', 'CX'),
    ('Territory of Norfolk Island', 'NF'),
    ('Territory of the Cocos (Keeling) Islands', 'CC'),
    ('Territory of the French Southern and Antarctic Lands', 'TF'),
    ('Territory of the Wallis and Futuna Islands', 'WF'),
    ('Thailand', 'TH'),
    ('Timor-Leste', 'TL'),
    ('Togo', 'TG'),
    ('Togolese Republic', 'TG'),
    ('Tokelau', 'TK'),
    ('Tonga', 'TO'),
    ('Trinidad and Tobago', 'TT'),
    ('Tunisia', 'TN'),
    ('Tunisian Republic', 'TN'),
    ('Türkiye', 'TR'),
    ('Turkmenistan', 'TM'),
    ('Turks and Caicos Islands', 'TC'),
    ('Tuvalu', 'TV'),
    ('Uganda', 'UG'),
    ('Ukraine', 'UA'),
    ('Union of the Comoros', 'KM'),
    ('United Arab Emirates', 'AE'),
    ('United Kingdom', 'GB'),
    ('United Kingdom of Great Britain and Northern Ireland', 'GB'),
    ('United Mexican States', 'MX'),
    ('United Republic of Tanzania', 'TZ'),
    ('United States', 'US'),
    ('United States Minor Outlying Islands', 'UM'),
    ('United States of America', 'US'),
    ('United States Virgin Islands', 'VI'),
    ('Uruguay', 'UY'),
    ('Uzbekistan', 'UZ'),
    ('Vanuatu', 'VU'),
    ('Vatican City', 'VA'),
    ('Vatican City State', 'VA'),
    ('Venezuela', 'VE'),
    ('Vietnam', 'VN'),
    ('Virgin Islands', 'VG'),
    ('Virgin Islands of the United States', 'VI'),
    ('Wallis and Futuna', 'WF'),
    ('Western Sahara', 'EH'),
    ('Yemen', 'YE'),
    ('Zambia', 'ZM'),
    ('Zimbabwe', 'ZW')
) AS m(name, code)
WHERE u.country = m.name;

-- providers.legal_country : country name -> ISO2 code
UPDATE providers AS p
SET legal_country = m.code
FROM (VALUES
    ('Afghanistan', 'AF'),
    ('Åland Islands', 'AX'),
    ('Albania', 'AL'),
    ('Algeria', 'DZ'),
    ('American Samoa', 'AS'),
    ('Andorra', 'AD'),
    ('Angola', 'AO'),
    ('Anguilla', 'AI'),
    ('Antarctica', 'AQ'),
    ('Antigua and Barbuda', 'AG'),
    ('Arab Republic of Egypt', 'EG'),
    ('Argentina', 'AR'),
    ('Argentine Republic', 'AR'),
    ('Armenia', 'AM'),
    ('Aruba', 'AW'),
    ('Australia', 'AU'),
    ('Austria', 'AT'),
    ('Azerbaijan', 'AZ'),
    ('Bahamas', 'BS'),
    ('Bahrain', 'BH'),
    ('Bailiwick of Guernsey', 'GG'),
    ('Bailiwick of Jersey', 'JE'),
    ('Bangladesh', 'BD'),
    ('Barbados', 'BB'),
    ('Belarus', 'BY'),
    ('Belgium', 'BE'),
    ('Belize', 'BZ'),
    ('Benin', 'BJ'),
    ('Bermuda', 'BM'),
    ('Bhutan', 'BT'),
    ('Bolivarian Republic of Venezuela', 'VE'),
    ('Bolivia', 'BO'),
    ('Bonaire, Sint Eustatius and Saba', 'BQ'),
    ('Bosnia and Herzegovina', 'BA'),
    ('Botswana', 'BW'),
    ('Bouvet Island', 'BV'),
    ('Brazil', 'BR'),
    ('British Indian Ocean Territory', 'IO'),
    ('British Virgin Islands', 'VG'),
    ('Brunei', 'BN'),
    ('Bulgaria', 'BG'),
    ('Burkina Faso', 'BF'),
    ('Burundi', 'BI'),
    ('Cambodia', 'KH'),
    ('Cameroon', 'CM'),
    ('Canada', 'CA'),
    ('Cape Verde', 'CV'),
    ('Caribbean Netherlands', 'BQ'),
    ('Cayman Islands', 'KY'),
    ('Central African Republic', 'CF'),
    ('Chad', 'TD'),
    ('Chile', 'CL'),
    ('China', 'CN'),
    ('Christmas Island', 'CX'),
    ('Co-operative Republic of Guyana', 'GY'),
    ('Cocos (Keeling) Islands', 'CC'),
    ('Collectivity of Saint Barthélemy', 'BL'),
    ('Colombia', 'CO'),
    ('Commonwealth of Australia', 'AU'),
    ('Commonwealth of Dominica', 'DM'),
    ('Commonwealth of Puerto Rico', 'PR'),
    ('Commonwealth of the Bahamas', 'BS'),
    ('Commonwealth of the Northern Mariana Islands', 'MP'),
    ('Comoros', 'KM'),
    ('Cook Islands', 'CK'),
    ('Costa Rica', 'CR'),
    ('Country of Curaçao', 'CW'),
    ('Croatia', 'HR'),
    ('Cuba', 'CU'),
    ('Curaçao', 'CW'),
    ('Cyprus', 'CY'),
    ('Czech Republic', 'CZ'),
    ('Czechia', 'CZ'),
    ('Democratic People''s Republic of Korea', 'KP'),
    ('Democratic Republic of São Tomé and Príncipe', 'ST'),
    ('Democratic Republic of the Congo', 'CD'),
    ('Democratic Republic of Timor-Leste', 'TL'),
    ('Democratic Socialist Republic of Sri Lanka', 'LK'),
    ('Denmark', 'DK'),
    ('Department of Mayotte', 'YT'),
    ('Djibouti', 'DJ'),
    ('Dominica', 'DM'),
    ('Dominican Republic', 'DO'),
    ('DR Congo', 'CD'),
    ('Ecuador', 'EC'),
    ('Egypt', 'EG'),
    ('El Salvador', 'SV'),
    ('Equatorial Guinea', 'GQ'),
    ('Eritrea', 'ER'),
    ('Estonia', 'EE'),
    ('Eswatini', 'SZ'),
    ('Ethiopia', 'ET'),
    ('Falkland Islands', 'FK'),
    ('Faroe Islands', 'FO'),
    ('Federal Democratic Republic of Ethiopia', 'ET'),
    ('Federal Democratic Republic of Nepal', 'NP'),
    ('Federal Republic of Germany', 'DE'),
    ('Federal Republic of Nigeria', 'NG'),
    ('Federal Republic of Somalia', 'SO'),
    ('Federated States of Micronesia', 'FM'),
    ('Federation of Saint Christopher and Nevis', 'KN'),
    ('Federative Republic of Brazil', 'BR'),
    ('Fiji', 'FJ'),
    ('Finland', 'FI'),
    ('France', 'FR'),
    ('French Guiana', 'GF'),
    ('French Polynesia', 'PF'),
    ('French Republic', 'FR'),
    ('French Southern and Antarctic Lands', 'TF'),
    ('Gabon', 'GA'),
    ('Gabonese Republic', 'GA'),
    ('Gambia', 'GM'),
    ('Georgia', 'GE'),
    ('Germany', 'DE'),
    ('Ghana', 'GH'),
    ('Gibraltar', 'GI'),
    ('Grand Duchy of Luxembourg', 'LU'),
    ('Greece', 'GR'),
    ('Greenland', 'GL'),
    ('Grenada', 'GD'),
    ('Guadeloupe', 'GP'),
    ('Guam', 'GU'),
    ('Guatemala', 'GT'),
    ('Guernsey', 'GG'),
    ('Guiana', 'GF'),
    ('Guinea', 'GN'),
    ('Guinea-Bissau', 'GW'),
    ('Guyana', 'GY'),
    ('Haiti', 'HT'),
    ('Hashemite Kingdom of Jordan', 'JO'),
    ('Heard Island and McDonald Islands', 'HM'),
    ('Hellenic Republic', 'GR'),
    ('Honduras', 'HN'),
    ('Hong Kong', 'HK'),
    ('Hong Kong Special Administrative Region of the People''s Republic of China', 'HK'),
    ('Hungary', 'HU'),
    ('Iceland', 'IS'),
    ('Independent and Sovereign Republic of Kiribati', 'KI'),
    ('Independent State of Papua New Guinea', 'PG'),
    ('Independent State of Samoa', 'WS'),
    ('India', 'IN'),
    ('Indonesia', 'ID'),
    ('Iran', 'IR'),
    ('Iraq', 'IQ'),
    ('Ireland', 'IE'),
    ('Islamic Republic of Afghanistan', 'AF'),
    ('Islamic Republic of Iran', 'IR'),
    ('Islamic Republic of Mauritania', 'MR'),
    ('Islamic Republic of Pakistan', 'PK'),
    ('Isle of Man', 'IM'),
    ('Israel', 'IL'),
    ('Italian Republic', 'IT'),
    ('Italy', 'IT'),
    ('Ivory Coast', 'CI'),
    ('Jamaica', 'JM'),
    ('Japan', 'JP'),
    ('Jersey', 'JE'),
    ('Jordan', 'JO'),
    ('Kazakhstan', 'KZ'),
    ('Kenya', 'KE'),
    ('Kingdom of Bahrain', 'BH'),
    ('Kingdom of Belgium', 'BE'),
    ('Kingdom of Bhutan', 'BT'),
    ('Kingdom of Cambodia', 'KH'),
    ('Kingdom of Denmark', 'DK'),
    ('Kingdom of Eswatini', 'SZ'),
    ('Kingdom of Lesotho', 'LS'),
    ('Kingdom of Morocco', 'MA'),
    ('Kingdom of Norway', 'NO'),
    ('Kingdom of Saudi Arabia', 'SA'),
    ('Kingdom of Spain', 'ES'),
    ('Kingdom of Sweden', 'SE'),
    ('Kingdom of Thailand', 'TH'),
    ('Kingdom of the Netherlands', 'NL'),
    ('Kingdom of Tonga', 'TO'),
    ('Kiribati', 'KI'),
    ('Kosovo', 'XK'),
    ('Kuwait', 'KW'),
    ('Kyrgyz Republic', 'KG'),
    ('Kyrgyzstan', 'KG'),
    ('Lao People''s Democratic Republic', 'LA'),
    ('Laos', 'LA'),
    ('Latvia', 'LV'),
    ('Lebanese Republic', 'LB'),
    ('Lebanon', 'LB'),
    ('Lesotho', 'LS'),
    ('Liberia', 'LR'),
    ('Libya', 'LY'),
    ('Liechtenstein', 'LI'),
    ('Lithuania', 'LT'),
    ('Luxembourg', 'LU'),
    ('Macao Special Administrative Region of the People''s Republic of China', 'MO'),
    ('Macau', 'MO'),
    ('Madagascar', 'MG'),
    ('Malawi', 'MW'),
    ('Malaysia', 'MY'),
    ('Maldives', 'MV'),
    ('Mali', 'ML'),
    ('Malta', 'MT'),
    ('Marshall Islands', 'MH'),
    ('Martinique', 'MQ'),
    ('Mauritania', 'MR'),
    ('Mauritius', 'MU'),
    ('Mayotte', 'YT'),
    ('Mexico', 'MX'),
    ('Micronesia', 'FM'),
    ('Moldova', 'MD'),
    ('Monaco', 'MC'),
    ('Mongolia', 'MN'),
    ('Montenegro', 'ME'),
    ('Montserrat', 'MS'),
    ('Morocco', 'MA'),
    ('Most Serene Republic of San Marino', 'SM'),
    ('Mozambique', 'MZ'),
    ('Myanmar', 'MM'),
    ('Namibia', 'NA'),
    ('Nation of Brunei, Abode of Peace', 'BN'),
    ('Nauru', 'NR'),
    ('Nepal', 'NP'),
    ('Netherlands', 'NL'),
    ('New Caledonia', 'NC'),
    ('New Zealand', 'NZ'),
    ('Nicaragua', 'NI'),
    ('Niger', 'NE'),
    ('Nigeria', 'NG'),
    ('Niue', 'NU'),
    ('Norfolk Island', 'NF'),
    ('North Korea', 'KP'),
    ('North Macedonia', 'MK'),
    ('Northern Mariana Islands', 'MP'),
    ('Norway', 'NO'),
    ('Oman', 'OM'),
    ('Oriental Republic of Uruguay', 'UY'),
    ('Pakistan', 'PK'),
    ('Palau', 'PW'),
    ('Palestine', 'PS'),
    ('Panama', 'PA'),
    ('Papua New Guinea', 'PG'),
    ('Paraguay', 'PY'),
    ('People''s Democratic Republic of Algeria', 'DZ'),
    ('People''s Republic of Bangladesh', 'BD'),
    ('People''s Republic of China', 'CN'),
    ('Peru', 'PE'),
    ('Philippines', 'PH'),
    ('Pitcairn Group of Islands', 'PN'),
    ('Pitcairn Islands', 'PN'),
    ('Plurinational State of Bolivia', 'BO'),
    ('Poland', 'PL'),
    ('Portugal', 'PT'),
    ('Portuguese Republic', 'PT'),
    ('Principality of Andorra', 'AD'),
    ('Principality of Liechtenstein', 'LI'),
    ('Principality of Monaco', 'MC'),
    ('Puerto Rico', 'PR'),
    ('Qatar', 'QA'),
    ('Republic of Albania', 'AL'),
    ('Republic of Angola', 'AO'),
    ('Republic of Armenia', 'AM'),
    ('Republic of Austria', 'AT'),
    ('Republic of Azerbaijan', 'AZ'),
    ('Republic of Belarus', 'BY'),
    ('Republic of Benin', 'BJ'),
    ('Republic of Botswana', 'BW'),
    ('Republic of Bulgaria', 'BG'),
    ('Republic of Burundi', 'BI'),
    ('Republic of Cabo Verde', 'CV'),
    ('Republic of Cameroon', 'CM'),
    ('Republic of Chad', 'TD'),
    ('Republic of Chile', 'CL'),
    ('Republic of China (Taiwan)', 'TW'),
    ('Republic of Colombia', 'CO'),
    ('Republic of Costa Rica', 'CR'),
    ('Republic of Côte d''Ivoire', 'CI'),
    ('Republic of Croatia', 'HR'),
    ('Republic of Cuba', 'CU'),
    ('Republic of Cyprus', 'CY'),
    ('Republic of Djibouti', 'DJ'),
    ('Republic of Ecuador', 'EC'),
    ('Republic of El Salvador', 'SV'),
    ('Republic of Equatorial Guinea', 'GQ'),
    ('Republic of Estonia', 'EE'),
    ('Republic of Fiji', 'FJ'),
    ('Republic of Finland', 'FI'),
    ('Republic of Ghana', 'GH'),
    ('Republic of Guatemala', 'GT'),
    ('Republic of Guinea', 'GN'),
    ('Republic of Guinea-Bissau', 'GW'),
    ('Republic of Haiti', 'HT'),
    ('Republic of Honduras', 'HN'),
    ('Republic of India', 'IN'),
    ('Republic of Indonesia', 'ID'),
    ('Republic of Iraq', 'IQ'),
    ('Republic of Ireland', 'IE'),
    ('Republic of Kazakhstan', 'KZ'),
    ('Republic of Kenya', 'KE'),
    ('Republic of Korea', 'KR'),
    ('Republic of Kosovo', 'XK'),
    ('Republic of Latvia', 'LV'),
    ('Republic of Liberia', 'LR'),
    ('Republic of Lithuania', 'LT'),
    ('Republic of Madagascar', 'MG'),
    ('Republic of Malawi', 'MW'),
    ('Republic of Mali', 'ML'),
    ('Republic of Malta', 'MT'),
    ('Republic of Mauritius', 'MU'),
    ('Republic of Moldova', 'MD'),
    ('Republic of Mozambique', 'MZ'),
    ('Republic of Namibia', 'NA'),
    ('Republic of Nauru', 'NR'),
    ('Republic of Nicaragua', 'NI'),
    ('Republic of Niger', 'NE'),
    ('Republic of North Macedonia', 'MK'),
    ('Republic of Palau', 'PW'),
    ('Republic of Panama', 'PA'),
    ('Republic of Paraguay', 'PY'),
    ('Republic of Peru', 'PE'),
    ('Republic of Poland', 'PL'),
    ('Republic of Rwanda', 'RW'),
    ('Republic of Senegal', 'SN'),
    ('Republic of Serbia', 'RS'),
    ('Republic of Seychelles', 'SC'),
    ('Republic of Sierra Leone', 'SL'),
    ('Republic of Singapore', 'SG'),
    ('Republic of Slovenia', 'SI'),
    ('Republic of South Africa', 'ZA'),
    ('Republic of South Sudan', 'SS'),
    ('Republic of Suriname', 'SR'),
    ('Republic of Tajikistan', 'TJ'),
    ('Republic of the Congo', 'CG'),
    ('Republic of the Gambia', 'GM'),
    ('Republic of the Maldives', 'MV'),
    ('Republic of the Marshall Islands', 'MH'),
    ('Republic of the Philippines', 'PH'),
    ('Republic of the Sudan', 'SD'),
    ('Republic of the Union of Myanmar', 'MM'),
    ('Republic of Trinidad and Tobago', 'TT'),
    ('Republic of Türkiye', 'TR'),
    ('Republic of Uganda', 'UG'),
    ('Republic of Uzbekistan', 'UZ'),
    ('Republic of Vanuatu', 'VU'),
    ('Republic of Yemen', 'YE'),
    ('Republic of Zambia', 'ZM'),
    ('Republic of Zimbabwe', 'ZW'),
    ('Réunion', 'RE'),
    ('Réunion Island', 'RE'),
    ('Romania', 'RO'),
    ('Russia', 'RU'),
    ('Russian Federation', 'RU'),
    ('Rwanda', 'RW'),
    ('Sahrawi Arab Democratic Republic', 'EH'),
    ('Saint Barthélemy', 'BL'),
    ('Saint Helena, Ascension and Tristan da Cunha', 'SH'),
    ('Saint Kitts and Nevis', 'KN'),
    ('Saint Lucia', 'LC'),
    ('Saint Martin', 'MF'),
    ('Saint Pierre and Miquelon', 'PM'),
    ('Saint Vincent and the Grenadines', 'VC'),
    ('Samoa', 'WS'),
    ('San Marino', 'SM'),
    ('São Tomé and Príncipe', 'ST'),
    ('Saudi Arabia', 'SA'),
    ('Senegal', 'SN'),
    ('Serbia', 'RS'),
    ('Seychelles', 'SC'),
    ('Sierra Leone', 'SL'),
    ('Singapore', 'SG'),
    ('Sint Maarten', 'SX'),
    ('Slovak Republic', 'SK'),
    ('Slovakia', 'SK'),
    ('Slovenia', 'SI'),
    ('Socialist Republic of Vietnam', 'VN'),
    ('Solomon Islands', 'SB'),
    ('Somalia', 'SO'),
    ('South Africa', 'ZA'),
    ('South Georgia', 'GS'),
    ('South Georgia and the South Sandwich Islands', 'GS'),
    ('South Korea', 'KR'),
    ('South Sudan', 'SS'),
    ('Spain', 'ES'),
    ('Sri Lanka', 'LK'),
    ('State of Eritrea', 'ER'),
    ('State of Israel', 'IL'),
    ('State of Kuwait', 'KW'),
    ('State of Libya', 'LY'),
    ('State of Palestine', 'PS'),
    ('State of Qatar', 'QA'),
    ('Sudan', 'SD'),
    ('Sultanate of Oman', 'OM'),
    ('Suriname', 'SR'),
    ('Svalbard and Jan Mayen', 'SJ'),
    ('Svalbard og Jan Mayen', 'SJ'),
    ('Sweden', 'SE'),
    ('Swiss Confederation', 'CH'),
    ('Switzerland', 'CH'),
    ('Syria', 'SY'),
    ('Syrian Arab Republic', 'SY'),
    ('Taiwan', 'TW'),
    ('Tajikistan', 'TJ'),
    ('Tanzania', 'TZ'),
    ('Territory of Christmas Island', 'CX'),
    ('Territory of Norfolk Island', 'NF'),
    ('Territory of the Cocos (Keeling) Islands', 'CC'),
    ('Territory of the French Southern and Antarctic Lands', 'TF'),
    ('Territory of the Wallis and Futuna Islands', 'WF'),
    ('Thailand', 'TH'),
    ('Timor-Leste', 'TL'),
    ('Togo', 'TG'),
    ('Togolese Republic', 'TG'),
    ('Tokelau', 'TK'),
    ('Tonga', 'TO'),
    ('Trinidad and Tobago', 'TT'),
    ('Tunisia', 'TN'),
    ('Tunisian Republic', 'TN'),
    ('Türkiye', 'TR'),
    ('Turkmenistan', 'TM'),
    ('Turks and Caicos Islands', 'TC'),
    ('Tuvalu', 'TV'),
    ('Uganda', 'UG'),
    ('Ukraine', 'UA'),
    ('Union of the Comoros', 'KM'),
    ('United Arab Emirates', 'AE'),
    ('United Kingdom', 'GB'),
    ('United Kingdom of Great Britain and Northern Ireland', 'GB'),
    ('United Mexican States', 'MX'),
    ('United Republic of Tanzania', 'TZ'),
    ('United States', 'US'),
    ('United States Minor Outlying Islands', 'UM'),
    ('United States of America', 'US'),
    ('United States Virgin Islands', 'VI'),
    ('Uruguay', 'UY'),
    ('Uzbekistan', 'UZ'),
    ('Vanuatu', 'VU'),
    ('Vatican City', 'VA'),
    ('Vatican City State', 'VA'),
    ('Venezuela', 'VE'),
    ('Vietnam', 'VN'),
    ('Virgin Islands', 'VG'),
    ('Virgin Islands of the United States', 'VI'),
    ('Wallis and Futuna', 'WF'),
    ('Western Sahara', 'EH'),
    ('Yemen', 'YE'),
    ('Zambia', 'ZM'),
    ('Zimbabwe', 'ZW')
) AS m(name, code)
WHERE p.legal_country = m.name;

-- parents.primary_nationality : demonym -> ISO2 code
UPDATE parents AS pa
SET primary_nationality = m.code
FROM (VALUES
    ('Afghan', 'AF'),
    ('Albanian', 'AL'),
    ('Algerian', 'DZ'),
    ('American', 'MP'),
    ('Andorran', 'AD'),
    ('Angolan', 'AO'),
    ('Argentine', 'AR'),
    ('Armenian', 'AM'),
    ('Australian', 'AU'),
    ('Austrian', 'AT'),
    ('Azerbaijani', 'AZ'),
    ('Bahamian', 'BS'),
    ('Bahraini', 'BH'),
    ('Bangladeshi', 'BD'),
    ('Barbadian', 'BB'),
    ('Belarusian', 'BY'),
    ('Belgian', 'BE'),
    ('Belizean', 'BZ'),
    ('Beninese', 'BJ'),
    ('Bhutanese', 'BT'),
    ('Bolivian', 'BO'),
    ('Bosnian', 'BA'),
    ('Brazilian', 'BR'),
    ('British', 'GB'),
    ('Bruneian', 'BN'),
    ('Bulgarian', 'BG'),
    ('Burkinabe', 'BF'),
    ('Burmese', 'MM'),
    ('Burundian', 'BI'),
    ('Cambodian', 'KH'),
    ('Cameroonian', 'CM'),
    ('Canadian', 'CA'),
    ('Cape Verdean', 'CV'),
    ('Central African', 'CF'),
    ('Chadian', 'TD'),
    ('Chilean', 'CL'),
    ('Chinese', 'CN'),
    ('Colombian', 'CO'),
    ('Comoran', 'KM'),
    ('Congolese', 'CD'),
    ('Costa Rican', 'CR'),
    ('Croatian', 'HR'),
    ('Cuban', 'CU'),
    ('Cypriot', 'CY'),
    ('Czech', 'CZ'),
    ('Danish', 'DK'),
    ('Djiboutian', 'DJ'),
    ('Dominican', 'DM'),
    ('Dutch', 'NL'),
    ('East Timorese', 'TL'),
    ('Ecuadorean', 'EC'),
    ('Egyptian', 'EG'),
    ('Emirati', 'AE'),
    ('Equatorial Guinean', 'GQ'),
    ('Eritrean', 'ER'),
    ('Estonian', 'EE'),
    ('Ethiopian', 'ET'),
    ('Fijian', 'FJ'),
    ('Filipino', 'PH'),
    ('Finnish', 'FI'),
    ('French', 'TF'),
    ('Gabonese', 'GA'),
    ('Gambian', 'GM'),
    ('Georgian', 'GE'),
    ('German', 'DE'),
    ('Ghanaian', 'GH'),
    ('Greek', 'GR'),
    ('Grenadian', 'GD'),
    ('Guatemalan', 'GT'),
    ('Guinean', 'GN'),
    ('Guyanese', 'GY'),
    ('Haitian', 'HT'),
    ('Honduran', 'HN'),
    ('Hungarian', 'HU'),
    ('Icelandic', 'IS'),
    ('Indian', 'IN'),
    ('Indonesian', 'ID'),
    ('Iranian', 'IR'),
    ('Iraqi', 'IQ'),
    ('Irish', 'IE'),
    ('Israeli', 'IL'),
    ('Italian', 'IT'),
    ('Ivorian', 'CI'),
    ('Jamaican', 'JM'),
    ('Japanese', 'JP'),
    ('Jordanian', 'JO'),
    ('Kazakhstani', 'KZ'),
    ('Kenyan', 'KE'),
    ('Kuwaiti', 'KW'),
    ('Kyrgyz', 'KG'),
    ('Laotian', 'LA'),
    ('Latvian', 'LV'),
    ('Lebanese', 'LB'),
    ('Liberian', 'LR'),
    ('Libyan', 'LY'),
    ('Liechtensteiner', 'LI'),
    ('Lithuanian', 'LT'),
    ('Luxembourger', 'LU'),
    ('Macedonian', 'MK'),
    ('Malagasy', 'MG'),
    ('Malawian', 'MW'),
    ('Malaysian', 'MY'),
    ('Maldivian', 'MV'),
    ('Malian', 'ML'),
    ('Maltese', 'MT'),
    ('Mauritanian', 'MR'),
    ('Mauritian', 'MU'),
    ('Mexican', 'MX'),
    ('Moldovan', 'MD'),
    ('Monacan', 'MC'),
    ('Mongolian', 'MN'),
    ('Montenegrin', 'ME'),
    ('Moroccan', 'MA'),
    ('Mozambican', 'MZ'),
    ('Namibian', 'NA'),
    ('Nepalese', 'NP'),
    ('New Zealander', 'NZ'),
    ('Nicaraguan', 'NI'),
    ('Nigerian', 'NG'),
    ('Nigerien', 'NE'),
    ('North Korean', 'KP'),
    ('Norwegian', 'NO'),
    ('Omani', 'OM'),
    ('Pakistani', 'PK'),
    ('Palauan', 'PW'),
    ('Palestinian', 'PS'),
    ('Panamanian', 'PA'),
    ('Papua New Guinean', 'PG'),
    ('Paraguayan', 'PY'),
    ('Peruvian', 'PE'),
    ('Polish', 'PL'),
    ('Portuguese', 'PT'),
    ('Qatari', 'QA'),
    ('Romanian', 'RO'),
    ('Russian', 'RU'),
    ('Rwandan', 'RW'),
    ('Saudi', 'SA'),
    ('Senegalese', 'SN'),
    ('Serbian', 'RS'),
    ('Singaporean', 'SG'),
    ('Slovak', 'SK'),
    ('Slovenian', 'SI'),
    ('Somali', 'SO'),
    ('South African', 'ZA'),
    ('South Korean', 'KR'),
    ('Spanish', 'ES'),
    ('Sri Lankan', 'LK'),
    ('Sudanese', 'SD'),
    ('Surinamese', 'SR'),
    ('Swazi', 'SZ'),
    ('Swedish', 'SE'),
    ('Swiss', 'CH'),
    ('Syrian', 'SY'),
    ('Taiwanese', 'TW'),
    ('Tajik', 'TJ'),
    ('Tanzanian', 'TZ'),
    ('Thai', 'TH'),
    ('Togolese', 'TG'),
    ('Trinidadian', 'TT'),
    ('Tunisian', 'TN'),
    ('Turkish', 'TR'),
    ('Turkmen', 'TM'),
    ('Ugandan', 'UG'),
    ('Ukrainian', 'UA'),
    ('Uruguayan', 'UY'),
    ('Uzbekistani', 'UZ'),
    ('Venezuelan', 'VE'),
    ('Vietnamese', 'VN'),
    ('Yemeni', 'YE'),
    ('Zambian', 'ZM'),
    ('Zimbabwean', 'ZW')
) AS m(demonym, code)
WHERE pa.primary_nationality = m.demonym;

-- parents.secondary_nationality : demonym -> ISO2 code
UPDATE parents AS pa
SET secondary_nationality = m.code
FROM (VALUES
    ('Afghan', 'AF'),
    ('Albanian', 'AL'),
    ('Algerian', 'DZ'),
    ('American', 'MP'),
    ('Andorran', 'AD'),
    ('Angolan', 'AO'),
    ('Argentine', 'AR'),
    ('Armenian', 'AM'),
    ('Australian', 'AU'),
    ('Austrian', 'AT'),
    ('Azerbaijani', 'AZ'),
    ('Bahamian', 'BS'),
    ('Bahraini', 'BH'),
    ('Bangladeshi', 'BD'),
    ('Barbadian', 'BB'),
    ('Belarusian', 'BY'),
    ('Belgian', 'BE'),
    ('Belizean', 'BZ'),
    ('Beninese', 'BJ'),
    ('Bhutanese', 'BT'),
    ('Bolivian', 'BO'),
    ('Bosnian', 'BA'),
    ('Brazilian', 'BR'),
    ('British', 'GB'),
    ('Bruneian', 'BN'),
    ('Bulgarian', 'BG'),
    ('Burkinabe', 'BF'),
    ('Burmese', 'MM'),
    ('Burundian', 'BI'),
    ('Cambodian', 'KH'),
    ('Cameroonian', 'CM'),
    ('Canadian', 'CA'),
    ('Cape Verdean', 'CV'),
    ('Central African', 'CF'),
    ('Chadian', 'TD'),
    ('Chilean', 'CL'),
    ('Chinese', 'CN'),
    ('Colombian', 'CO'),
    ('Comoran', 'KM'),
    ('Congolese', 'CD'),
    ('Costa Rican', 'CR'),
    ('Croatian', 'HR'),
    ('Cuban', 'CU'),
    ('Cypriot', 'CY'),
    ('Czech', 'CZ'),
    ('Danish', 'DK'),
    ('Djiboutian', 'DJ'),
    ('Dominican', 'DM'),
    ('Dutch', 'NL'),
    ('East Timorese', 'TL'),
    ('Ecuadorean', 'EC'),
    ('Egyptian', 'EG'),
    ('Emirati', 'AE'),
    ('Equatorial Guinean', 'GQ'),
    ('Eritrean', 'ER'),
    ('Estonian', 'EE'),
    ('Ethiopian', 'ET'),
    ('Fijian', 'FJ'),
    ('Filipino', 'PH'),
    ('Finnish', 'FI'),
    ('French', 'TF'),
    ('Gabonese', 'GA'),
    ('Gambian', 'GM'),
    ('Georgian', 'GE'),
    ('German', 'DE'),
    ('Ghanaian', 'GH'),
    ('Greek', 'GR'),
    ('Grenadian', 'GD'),
    ('Guatemalan', 'GT'),
    ('Guinean', 'GN'),
    ('Guyanese', 'GY'),
    ('Haitian', 'HT'),
    ('Honduran', 'HN'),
    ('Hungarian', 'HU'),
    ('Icelandic', 'IS'),
    ('Indian', 'IN'),
    ('Indonesian', 'ID'),
    ('Iranian', 'IR'),
    ('Iraqi', 'IQ'),
    ('Irish', 'IE'),
    ('Israeli', 'IL'),
    ('Italian', 'IT'),
    ('Ivorian', 'CI'),
    ('Jamaican', 'JM'),
    ('Japanese', 'JP'),
    ('Jordanian', 'JO'),
    ('Kazakhstani', 'KZ'),
    ('Kenyan', 'KE'),
    ('Kuwaiti', 'KW'),
    ('Kyrgyz', 'KG'),
    ('Laotian', 'LA'),
    ('Latvian', 'LV'),
    ('Lebanese', 'LB'),
    ('Liberian', 'LR'),
    ('Libyan', 'LY'),
    ('Liechtensteiner', 'LI'),
    ('Lithuanian', 'LT'),
    ('Luxembourger', 'LU'),
    ('Macedonian', 'MK'),
    ('Malagasy', 'MG'),
    ('Malawian', 'MW'),
    ('Malaysian', 'MY'),
    ('Maldivian', 'MV'),
    ('Malian', 'ML'),
    ('Maltese', 'MT'),
    ('Mauritanian', 'MR'),
    ('Mauritian', 'MU'),
    ('Mexican', 'MX'),
    ('Moldovan', 'MD'),
    ('Monacan', 'MC'),
    ('Mongolian', 'MN'),
    ('Montenegrin', 'ME'),
    ('Moroccan', 'MA'),
    ('Mozambican', 'MZ'),
    ('Namibian', 'NA'),
    ('Nepalese', 'NP'),
    ('New Zealander', 'NZ'),
    ('Nicaraguan', 'NI'),
    ('Nigerian', 'NG'),
    ('Nigerien', 'NE'),
    ('North Korean', 'KP'),
    ('Norwegian', 'NO'),
    ('Omani', 'OM'),
    ('Pakistani', 'PK'),
    ('Palauan', 'PW'),
    ('Palestinian', 'PS'),
    ('Panamanian', 'PA'),
    ('Papua New Guinean', 'PG'),
    ('Paraguayan', 'PY'),
    ('Peruvian', 'PE'),
    ('Polish', 'PL'),
    ('Portuguese', 'PT'),
    ('Qatari', 'QA'),
    ('Romanian', 'RO'),
    ('Russian', 'RU'),
    ('Rwandan', 'RW'),
    ('Saudi', 'SA'),
    ('Senegalese', 'SN'),
    ('Serbian', 'RS'),
    ('Singaporean', 'SG'),
    ('Slovak', 'SK'),
    ('Slovenian', 'SI'),
    ('Somali', 'SO'),
    ('South African', 'ZA'),
    ('South Korean', 'KR'),
    ('Spanish', 'ES'),
    ('Sri Lankan', 'LK'),
    ('Sudanese', 'SD'),
    ('Surinamese', 'SR'),
    ('Swazi', 'SZ'),
    ('Swedish', 'SE'),
    ('Swiss', 'CH'),
    ('Syrian', 'SY'),
    ('Taiwanese', 'TW'),
    ('Tajik', 'TJ'),
    ('Tanzanian', 'TZ'),
    ('Thai', 'TH'),
    ('Togolese', 'TG'),
    ('Trinidadian', 'TT'),
    ('Tunisian', 'TN'),
    ('Turkish', 'TR'),
    ('Turkmen', 'TM'),
    ('Ugandan', 'UG'),
    ('Ukrainian', 'UA'),
    ('Uruguayan', 'UY'),
    ('Uzbekistani', 'UZ'),
    ('Venezuelan', 'VE'),
    ('Vietnamese', 'VN'),
    ('Yemeni', 'YE'),
    ('Zambian', 'ZM'),
    ('Zimbabwean', 'ZW')
) AS m(demonym, code)
WHERE pa.secondary_nationality = m.demonym;

COMMIT;
