import type { CancellationPolicyCustomData } from '@world-schools/wc-types'
import { buildCancellationPolicyRows, getCancellationPolicyLabel } from '@world-schools/wc-utils'
import type { AgeGroup, Camp } from '../types/camps'
import type { CampBookingAddOn } from '../types/camp-booking'

export interface FaqItem {
  question: string
  answer: string
}

/**
 * FAQ Item 1 — Ages
 * Condition: camp.ageGroups has at least one entry
 */
export function buildAgesFaq(ageGroups: AgeGroup[]): FaqItem | null {
  if (!ageGroups?.length) return null
  const minAge = Math.min(...ageGroups.map(g => g.min))
  const maxAge = Math.max(...ageGroups.map(g => g.max))
  return {
    question: 'What ages is this camp for?',
    answer: `This camp is open to children aged ${minAge} to ${maxAge}.`,
  }
}

/**
 * FAQ Item 2 — Residential vs day
 * Condition: Always shown
 */
export function buildTypeFaq(type: Camp['type']): FaqItem {
  return {
    question: 'Is this a residential or day camp?',
    answer:
      type === 'residential'
        ? 'This is a residential camp. Children stay on-site in supervised accommodation for the full duration of their session.'
        : 'This is a day camp. Children attend during the day and return home each evening.',
  }
}

/**
 * FAQ Item 3 — Activities
 * Condition: camp.campFocus?.primaryFocus exists
 */
export function buildActivitiesFaq(campFocus: Camp['campFocus']): FaqItem | null {
  const primary = campFocus?.primaryFocus?.activityName
  if (!primary) return null

  const extras: string[] = (campFocus?.additionalFocuses ?? [])
    .map((f: any) => f.activityName)
    .filter(Boolean)

  let answer: string
  if (extras.length === 0) {
    answer = `The main focus of this camp is ${primary}.`
  } else if (extras.length === 1) {
    answer = `The main focus of this camp is ${primary}. Children also take part in ${extras[0]}.`
  } else {
    const rest = extras.slice(0, -1).join(', ')
    const last = extras[extras.length - 1]
    answer = `The main focus of this camp is ${primary}. Children also take part in ${rest} and ${last}.`
  }

  return { question: 'What activities will my child do?', answer }
}

/**
 * FAQ Item 4 — What's included
 * Condition: combined included item list is non-empty
 */
export function buildIncludedFaq(whatsIncluded: Camp['whatsIncluded']): FaqItem | null {
  if (!whatsIncluded) return null

  const items: string[] = [...(whatsIncluded.manual ?? []), ...(whatsIncluded.autoGenerated ?? [])]
    .filter((item: any) => item.isSelected)
    .map((item: any) => item.text)

  if (!items.length) return null

  const last = items[items.length - 1]
  const rest = items.slice(0, -1)
  const answer =
    rest.length === 0
      ? `The camp fee includes ${last}.`
      : `The camp fee includes ${rest.join(', ')}, and ${last}.`

  return { question: "What's included in the price?", answer }
}

/**
 * FAQ Item 5 — Meals
 * Condition: camp.meals exists with mealTypes
 */
export function buildMealsFaq(meals: Camp['meals']): FaqItem | null {
  if (!meals) return null

  const mealTypes: string[] = meals.mealTypes ?? []
  if (!mealTypes.length) return null

  const mealNames = mealTypes.map((m: string) => m.charAt(0).toUpperCase() + m.slice(1))
  const dietaryOptions: string[] = meals.dietaryOptions ?? []
  const dietaryNote =
    dietaryOptions.length > 0 ? ` Dietary options available: ${dietaryOptions.join(', ')}.` : ''

  return {
    question: 'What meals are provided?',
    answer: `Included meals: ${mealNames.join(', ')}.${dietaryNote}`,
  }
}

/**
 * FAQ Item 6 — Cancellation policy
 * Condition: camp.provider.settings.cancellationPolicy exists
 */
export function buildCancellationFaq(
  cancellationPolicy: string | null | undefined,
  cancellationPolicyCustom?: CancellationPolicyCustomData | null
): FaqItem | null {
  if (!cancellationPolicy) return null

  const rows = buildCancellationPolicyRows(cancellationPolicy, cancellationPolicyCustom)
  if (rows.length === 0) return null

  const ruleLines = rows.map(r => `${r.rangeLabel}: ${r.refundLabel}`)
  const label = getCancellationPolicyLabel(cancellationPolicy)

  return {
    question: 'What is the cancellation policy?',
    answer: `${label} policy: ${ruleLines.join('; ')}.`,
  }
}

/**
 * FAQ Item 7 — Transport
 * Condition: addOns contains a transport-related add-on
 */
export function buildTransportFaq(addOns: CampBookingAddOn[], currency?: string): FaqItem | null {
  if (!addOns?.length) return null

  const transportAddon = addOns.find(a => /transport|coach|transfer|shuttle|pickup/i.test(a.name))
  if (!transportAddon) return null

  const price = new Intl.NumberFormat('en-GB', {
    style: 'currency',
    currency: transportAddon.currency ?? currency ?? 'EUR',
    maximumFractionDigits: 0,
  }).format(transportAddon.price)

  return {
    question: 'Is transport to the camp available?',
    answer: `Yes — ${transportAddon.name} is available as an optional add-on for ${price}. You can select it during the booking process.`,
  }
}
